version: '3.7'

services:
  openvpn3:
    image: .
    build: openvpnc/.
    privileged: true
    entrypoint: ["openvpn", "--config", "/home/client.ovpn"]
    volumes:
      - openvpn3:/home
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  openvpn3:

