version: "3.9"  # optional since v1.27.0
services:
  openvpn3:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
      - logvolume01:/var/log
    links:
      - redis
volumes:
  logvolume01: {}
